-- MySQL Script generated by MySQL Workbench
-- Sun Feb  7 10:09:29 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema intendev_projectrun
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema intendev_projectrun
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `intendev_projectrun` DEFAULT CHARACTER SET utf8 ;
USE `intendev_projectrun` ;

-- -----------------------------------------------------
-- Table `intendev_projectrun`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intendev_projectrun`.`users` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `gender` INT NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;

ALTER TABLE `intendev_projectrun`.`users`
ADD COLUMN `activated` TINYINT NOT NULL AFTER `gender`;

-- -----------------------------------------------------
-- Table `intendev_projectrun`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intendev_projectrun`.`friends` (
  `email` VARCHAR(45) NOT NULL,
  `prefferedName` VARCHAR(45) NOT NULL,
  `blocked` TINYINT(1) NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `email_FK`
    FOREIGN KEY (`email`)
    REFERENCES `intendev_projectrun`.`users` (`email`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intendev_projectrun`.`interests_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intendev_projectrun`.`interests_type` (
  `reading` TINYINT(1) NOT NULL,
  `writing` TINYINT(1) NOT NULL,
  `playing` TINYINT(1) NOT NULL,
  `tv_shows` TINYINT(1) NOT NULL,
  `other` TINYINT(1) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intendev_projectrun`.`interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intendev_projectrun`.`interest` (
  `type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Other` VARCHAR(45) NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intendev_projectrun`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intendev_projectrun`.`chat` (
  `messegeid` INT NOT NULL,
  `emailfrom` VARCHAR(45) NOT NULL,
  `emailto` VARCHAR(45) NOT NULL,
  `messege` LONGTEXT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`messegeid`),
  INDEX `emailfrom_FK_idx` (`emailfrom` ASC),
  INDEX `emailto_FK_idx` (`emailto` ASC),
  CONSTRAINT `emailfrom_FK`
    FOREIGN KEY (`emailfrom`)
    REFERENCES `intendev_projectrun`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emailto_FK`
    FOREIGN KEY (`emailto`)
    REFERENCES `intendev_projectrun`.`users` (`email`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intendev_projectrun`.`voip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intendev_projectrun`.`voip` (
  `callid` INT NOT NULL,
  `emailfrom` VARCHAR(45) NOT NULL,
  `emailto` VARCHAR(45) NOT NULL,
  `missed` TINYINT(1) NOT NULL,
  `rejected` TINYINT(1) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `duration` DATETIME NOT NULL,
  PRIMARY KEY (`callid`),
  INDEX `emailfrom_FK_idx` (`emailfrom` ASC),
  INDEX `emailto_FK_idx` (`emailto` ASC),
  CONSTRAINT `emailfromvoip_FK`
    FOREIGN KEY (`emailfrom`)
    REFERENCES `intendev_projectrun`.`users` (`email`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `emailtovoip_FK`
    FOREIGN KEY (`emailto`)
    REFERENCES `intendev_projectrun`.`users` (`email`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intendev_projectrun`.`hasFriends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intendev_projectrun`.`hasFriends` (
  `friendshipid` INT NOT NULL,
  `email1` VARCHAR(45) NOT NULL,
  `email2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`friendshipid`),
  INDEX `email1_FK_idx` (`email1` ASC),
  INDEX `email2_FK_idx` (`email2` ASC),
  CONSTRAINT `email1_FK`
    FOREIGN KEY (`email1`)
    REFERENCES `intendev_projectrun`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `email2_FK`
    FOREIGN KEY (`email2`)
    REFERENCES `intendev_projectrun`.`users` (`email`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intendev_projectrun`.`hasInterest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intendev_projectrun`.`hasInterest` (
  `idhasInterest` INT NOT NULL,
  `idInterest` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idhasInterest`),
  INDEX `email_FK_idx` (`email` ASC),
  CONSTRAINT `emailInt_FK`
    FOREIGN KEY (`email`)
    REFERENCES `intendev_projectrun`.`users` (`email`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;